"allocate_workspace_items                                                ",&
"cholesky_saxpy                                                          ",&
"dbl1_alloc                                                              ",&
"dbl1_dealloc                                                            ",&
"dbl2_alloc                                                              ",&
"dbl2_dealloc                                                            ",&
"dbl3_alloc                                                              ",&
"dbl3dealloc                                                             ",&
"dbl4_alloc                                                              ",&
"dbl4dealloc                                                             ",&
"estimate_worst_frac                                                     ",&
"fill_sort_strings_and_sort                                              ",&
"find_max_rel_diff                                                       ",&
"find_means_and_variances                                                ",&
"house                                                                   ",&
"householder_ols                                                         ",&
"householder_qr                                                          ",&
"householder_qr2                                                         ",&
"householder_qr2_pivot                                                   ",&
"householder_qr_pivot                                                    ",&
"initgn                                                                  ",&
"int1_alloc                                                              ",&
"int1_dealloc                                                            ",&
"int2_alloc                                                              ",&
"int2_dealloc                                                            ",&
"int3_alloc                                                              ",&
"int3_dealloc                                                            ",&
"invert_lower                                                            ",&
"log1_alloc                                                              ",&
"log1_dealloc                                                            ",&
"log2_alloc                                                              ",&
"log2_dealloc                                                            ",&
"log3_alloc                                                              ",&
"log3_dealloc                                                            ",&
"make_xsort_and_ysort                                                    ",&
"make_xtxinv                                                             ",&
"matmul_boundcheck                                                       ",&
"mltmod                                                                  ",&
"nullify_workspace_type                                                  ",&
"premult_lower_by_transpose                                              ",&
"qsort_double                                                            ",&
"qsort_integer                                                           ",&
"qsort_strings                                                           ",&
"ran_genchi                                                              ",&
"ran_gengam                                                              ",&
"ran_genint                                                              ",&
"ran_genunf                                                              ",&
"ran_phrasd                                                              ",&
"ran_setall                                                              ",&
"ran_sexp                                                                ",&
"ran_sgamma                                                              ",&
"ran_snorm                                                               ",&
"ran_timeseed                                                            ",&
"regress_univariate                                                      ",&
"row_house                                                               ",&
"row_house_vec                                                           ",&
"run_estep                                                               ",&
"run_istep                                                               ",&
"run_mstep                                                               ",&
"run_norm_engine_em                                                      ",&
"run_norm_engine_impute_mean                                             ",&
"run_norm_engine_impute_random                                           ",&
"run_norm_engine_logpost                                                 ",&
"run_norm_engine_mcmc                                                    ",&
"run_pstep                                                               ",&
"sort_cases_by_missingness                                               ",&
"str1_alloc                                                              ",&
"str1_dealloc                                                            ",&
"str2_alloc                                                              ",&
"str2_dealloc                                                            ",&
"str3_alloc                                                              ",&
"str3_dealloc                                                            ",&
"sweep_forward                                                           ",&
"sweep_reverse                                                           ",&
"update_rates                                                            ",&
"update_theta                                                            ",&
"update_theta_and_oldtheta                                               ",&
